### ISSUE TITLE
Crash safety is compromised, causing data loss

### ISSUE THREAD

**Issue by lizhanhui** [AutoMQ/automq-for-rocketmq#573]
2023-11-06 10:58:00 ERROR Failed to start broker, try to shutdown
java.lang.RuntimeException: java.lang.IllegalStateException: [BUG] WAL data may lost, streamId 64 endOffset=10498 from controllerbut WAL recovered records startOffset=10499
        at com.automq.stream.s3.S3Storage.startup(S3Storage.java:119) ~[classes/:?]
        at com.automq.rocketmq.store.S3StreamStore.start(S3StreamStore.java:183) ~[classes/:?]
        at com.automq.rocketmq.store.MessageStoreImpl.start(MessageStoreImpl.java:107) ~[classes/:?]
        at com.automq.rocketmq.broker.BrokerController.start(BrokerController.java:98) ~[classes/:?]
        at com.automq.rocketmq.broker.BrokerStartup.start(BrokerStartup.java:97) [classes/:?]
        at com.automq.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:90) [classes/:?]
Caused by: java.lang.IllegalStateException: [BUG] WAL data may lost, streamId 64 endOffset=10498 from controllerbut WAL recovered records startOffset=10499
        at com.automq.stream.s3.S3Storage.lambda$recoverContinuousRecords$4(S3Storage.java:195) ~[classes/:?]
        at java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at com.automq.stream.s3.S3Storage.recoverContinuousRecords(S3Storage.java:190) ~[classes/:?]
        at com.automq.stream.s3.S3Storage.recover(S3Storage.java:130) ~[classes/:?]
        at com.automq.stream.s3.S3Storage.startup(S3Storage.java:115) ~[classes/:?]
        ... 5 more

**Comment by superhx** [comment]
Potential buggy code:
1. Suppose block_size=4096, when record0 (bytes=0..4500) record1 (bytes=4500..4510) record2 (bytes=4510..4520) and the trim offset is 4500.
2. Expect log recovery will return record2. But the cause of `readRecord` from 4096 fails, the recovery will jump to the next block whose offset is 12288, and then record2 is lost.

![image](https://github.com/AutoMQ/automq-for-rocketmq/assets/5719209/ee4a1625-7dd5-48b5-98b5-5e9b2b439b1e)
