### ISSUE TITLE
ConsumeMessage missing the SubMode

### ISSUE THREAD

**Issue by leizhiyuan** [AutoMQ/automq-for-rocketmq#607]
```
[grpc-default-executor-0] INFO com.automq.rocketmq.controller.client.GrpcControllerClient - CreateGroup request is rejected. Reason: SubMode is required
java.util.concurrent.CompletionException: com.automq.rocketmq.common.exception.ControllerException: SubMode is required
	at com.automq.rocketmq.cli.ConsumeMessage.lambda$prepareConsumerGroup$5(ConsumeMessage.java:191)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at com.automq.rocketmq.controller.client.GrpcControllerClient$10.onSuccess(GrpcControllerClient.java:495)
	at com.automq.rocketmq.controller.client.GrpcControllerClient$10.onSuccess(GrpcControllerClient.java:480)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1133)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1286)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1055)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:782)
	at io.grpc.stub.ClientCalls$GrpcFuture.set(ClientCalls.java:563)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:536)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:567)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:71)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:735)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:716)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.automq.rocketmq.common.exception.ControllerException: SubMode is required
	at com.automq.rocketmq.controller.client.GrpcControllerClient$10.onSuccess(GrpcControllerClient.java:494)
	... 20 more
```

**Comment by ShadowySpirits** [comment]
Please update your code, this issue has been fixed at https://github.com/AutoMQ/automq-for-rocketmq/commit/0f86ed8e99974348dec682ea6a35ff14b0627269.
