### ISSUE TITLE
consumer can not consume

### ISSUE THREAD

**Issue by mooc9988** [AutoMQ/automq-for-rocketmq#814]
can not fetch from block cache:
```
[2023-12-08 03:06:03,389] ERROR read 27661 [390912, 1012772) from block cache fail (com.automq.stream.s3.cache.DefaultS3BlockCache)
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: read size 580777221 exceeds max inflight read size 134217728
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1177)
        at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2320)
        at com.automq.stream.s3.cache.StreamReader.handleSyncReadAhead(StreamReader.java:147)
        at com.automq.stream.s3.cache.StreamReader.lambda$syncReadAhead$0(StreamReader.java:115)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalArgumentException: read size 580777221 exceeds max inflight read size 134217728
        at com.automq.stream.s3.cache.InflightReadThrottle.acquire(InflightReadThrottle.java:88)
        at com.automq.stream.s3.cache.StreamReader.handleSyncReadAhead(StreamReader.java:146)
        ... 6 more
[2023-12-08 03:06:03,390] ERROR read from block cache failed, stream=27661, 390912-131072, maxBytes: {} (com.automq.stream.s3.S3Storage)
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: read size 580777221 exceeds max inflight read size 134217728
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1177)
        at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2320)
        at com.automq.stream.s3.cache.StreamReader.handleSyncReadAhead(StreamReader.java:147)
        at com.automq.stream.s3.cache.StreamReader.lambda$syncReadAhead$0(StreamReader.java:115)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalArgumentException: read size 580777221 exceeds max inflight read size 134217728
        at com.automq.stream.s3.cache.InflightReadThrottle.acquire(InflightReadThrottle.java:88)
        at com.automq.stream.s3.cache.StreamReader.handleSyncReadAhead(StreamReader.java:146)
        ... 6 more
[2023-12-08 03:06:03,391] ERROR [Stream id=27661 epoch=4] stream fetch [390912, 1012772) 131072 fail (com.automq.stream.s3.S3Stream)
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: read size 580777221 exceeds max inflight read size 134217728
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1177)
        at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2320)
        at com.automq.stream.s3.cache.StreamReader.handleSyncReadAhead(StreamReader.java:147)
        at com.automq.stream.s3.cache.StreamReader.lambda$syncReadAhead$0(StreamReader.java:115)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalArgumentException: read size 580777221 exceeds max inflight read size 134217728
        at com.automq.stream.s3.cache.InflightReadThrottle.acquire(InflightReadThrottle.java:88)
        at com.automq.stream.s3.cache.StreamReader.handleSyncReadAhead(StreamReader.java:146)
        ... 6 more
[2023-12-08 03:06:03,392] ERROR Fetch stream[27661] [390912,1012772) fail (kafka.log.streamaspect.AlwaysSuccessClient)
java.lang.IllegalArgumentException: read size 580777221 exceeds max inflight read size 134217728
        at com.automq.stream.s3.cache.InflightReadThrottle.acquire(InflightReadThrottle.java:88)
        at com.automq.stream.s3.cache.StreamReader.handleSyncReadAhead(StreamReader.java:146)
        at com.automq.stream.s3.cache.StreamReader.lambda$syncReadAhead$0(StreamReader.java:115)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
[2023-12-08 03:06:03,392] ERROR [ReplicaManager broker=0] Error processing fetch with max size 131072 from consumer on partition iB5eSO1zTR2hxLGpPtL0jw:testMain-3: PartitionData(topicId=iB5eSO1zTR2hxLGpPtL0jw, fetchOffset=390912, logStartOffset=-1, maxBytes=131072, currentLeaderEpoch=Optional[4], lastFetchedEpoch=Optional.empty) (kafka.server.ReplicaManager)
java.lang.IllegalArgumentException: read size 580777221 exceeds max inflight read size 134217728
        at com.automq.stream.s3.cache.InflightReadThrottle.acquire(InflightReadThrottle.java:88)
        at com.automq.stream.s3.cache.StreamReader.handleSyncReadAhead(StreamReader.java:146)
        at com.automq.stream.s3.cache.StreamReader.lambda$syncReadAhead$0(StreamReader.java:115)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

Memory leadk is also found:
```
[2023-12-08 03:06:30,910] ERROR LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
        io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:403)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
        com.automq.stream.s3.DirectByteBufAlloc.byteBuffer(DirectByteBufAlloc.java:50)
        com.automq.stream.s3.DirectByteBufAlloc.byteBuffer(DirectByteBufAlloc.java:42)
        com.automq.stream.s3.StreamRecordBatchCodec.decode(StreamRecordBatchCodec.java:65)
        com.automq.stream.s3.ObjectReader$DataBlock$1.next(ObjectReader.java:311)
        com.automq.stream.s3.ObjectReader$DataBlock$1.next(ObjectReader.java:299)
        com.automq.stream.s3.cache.DataBlockRecords.complete(DataBlockRecords.java:49)
        com.automq.stream.s3.cache.DataBlockReadAccumulator.lambda$readDataBlock$1(DataBlockReadAccumulator.java:83)
        java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        com.automq.stream.s3.operator.DefaultS3Operator$MergedReadTask.handleReadCompleted(DefaultS3Operator.java:739)
        com.automq.stream.s3.operator.DefaultS3Operator.lambda$tryMergeRead0$3(DefaultS3Operator.java:247)
        com.automq.stream.utils.FutureUtil.suppress(FutureUtil.java:37)
        com.automq.stream.s3.operator.DefaultS3Operator.lambda$tryMergeRead0$4(DefaultS3Operator.java:247)
        java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        com.automq.stream.s3.operator.DefaultS3Operator.lambda$acquireReadPermit$38(DefaultS3Operator.java:626)
        java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        java.base/java.lang.Thread.run(Thread.java:840) (io.netty.util.ResourceLeakDetector)
```

**Comment by mooc9988** [comment]
Fixed by #816
